"use client"

import { useEffect, useState } from "react"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { ServiceManager } from "@/components/admin/service-manager"
import { LayoutDashboard, Inbox, CalendarDays, Users, BriefcaseBusiness, Settings, Search, CheckCircle2 } from "lucide-react"

type Inquiry={id:string;name:string;email:string;phone:string|null;service:string;budget:string|null;message:string;status:string;admin_reply:string|null;replied_at:string|null;created_at:string}
type Booking={id:string;user_id:string;service_id:string;scheduled_start:string;scheduled_end:string;status:string;notes:string|null;created_at:string;services?:{title:string}|{title:string}[]|null}
type Customer={name:string;email:string;phone:string|null;bookings:number;inquiries:number;lastActivity:string;history:unknown[]}
type Overview={totalRequests:number;newInquiries:number;pendingBookings:number;confirmedBookings:number;todaysAppointments:number;totalCustomers:number}

const nav=[['overview','Overview',LayoutDashboard],['requests','Requests',Inbox],['appointments','Appointments',CalendarDays],['customers','Customers',Users],['services','Services',BriefcaseBusiness],['settings','Settings',Settings]] as const

export default function AdminPage(){
 const [view,setView]=useState('overview'),[inquiries,setInquiries]=useState<Inquiry[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[overview,setOverview]=useState<Overview|null>(null),[selected,setSelected]=useState<Inquiry|null>(null),[reply,setReply]=useState(''),[service,setService]=useState('all'),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(){
  try{const qs=new URLSearchParams();if(service!=='all')qs.set('service',service);if(status!=='all')qs.set('status',status);const [o,i,b,c]=await Promise.all([fetch('/api/admin/overview'),fetch('/api/admin/inquiries'),fetch(`/api/admin/bookings?${qs}`),fetch(`/api/admin/customers?search=${encodeURIComponent(search)}`)]);if([o,i,b,c].some(r=>r.status===401||r.status===403)){window.location.href='/login?next=/admin';return}const [od,id,bd,cd]=await Promise.all([o.json(),i.json(),b.json(),c.json()]);if(!o.ok||!i.ok||!b.ok||!c.ok)throw new Error('Unable to load dashboard');setOverview(od);setInquiries(id);setBookings(bd);setCustomers(cd)}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[service,status])
 async function updateInquiry(id:string,patch:Record<string,string>){const r=await fetch('/api/admin/inquiries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})});if(!r.ok)return setError('Unable to update request');setSelected(null);setReply('');void load()}
 async function updateBooking(id:string,next:string){const r=await fetch('/api/admin/bookings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:next})});if(!r.ok)setError('Unable to update appointment');else void load()}
 if(loading)return <div className="flex min-h-screen items-center justify-center">Loading dashboard...</div>
 return <><Navigation/><main className="min-h-screen bg-muted/20 pt-24 pb-16"><div className="mx-auto flex max-w-7xl gap-6 px-4 sm:px-6 lg:px-8">
  <aside className="hidden w-56 shrink-0 lg:block"><div className="sticky top-24 rounded-xl bg-sidebar p-3 text-sidebar-foreground"><p className="px-3 pb-4 text-lg font-bold">Point 63 <span className="text-sidebar-primary">Admin</span></p><nav className="flex flex-col gap-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm ${view===id?'bg-sidebar-primary text-sidebar-primary-foreground':'text-sidebar-foreground/75 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground'}`}><Icon data-icon="inline-start"/>{label}</button>)}</nav></div></aside>
  <div className="min-w-0 flex-1"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Administration</p><h1 className="mt-1 text-3xl font-bold">{nav.find(([id])=>id===view)?.[1] || 'Dashboard'}</h1></div><div className="flex gap-2 lg:hidden"><Select value={view} onValueChange={setView}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{nav.map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div></div>
   {error&&<p className="mb-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
   {view==='overview'&&overview&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[['Total Requests',overview.totalRequests],['New Inquiries',overview.newInquiries],['Pending Bookings',overview.pendingBookings],['Confirmed Bookings',overview.confirmedBookings],['Today\'s Appointments',overview.todaysAppointments],['Total Customers',overview.totalCustomers]].map(([label,value])=><Card key={label as string}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></CardContent></Card>)}</div><Card className="mt-6"><CardHeader><CardTitle>Recent activity</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{inquiries.slice(0,6).map(item=><div key={item.id} className="flex items-center justify-between gap-4 border-b pb-3 text-sm last:border-0"><div><p className="font-medium">{item.name}</p><p className="text-muted-foreground">{item.type==='inquiry'?'New inquiry':'Booking request'} · {item.email}</p></div><Badge variant="outline">{item.status}</Badge></div>)}</CardContent></Card></>}
   {view==='requests'&&<Card><CardHeader><CardTitle>Requests</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex flex-wrap gap-2"><Input className="max-w-xs" placeholder="Search requests" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue placeholder="Status"/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{['new','read','pending','confirmed','replied','completed','cancelled','closed'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void load()}><Search data-icon="inline-start"/>Search</Button></div>{inquiries.map(x=><button key={x.id} onClick={()=>{setSelected(x);setReply(x.admin_reply||'')}} className="rounded-lg border p-4 text-left hover:bg-muted/40"><div className="flex justify-between gap-3"><span className="font-medium">{x.name}</span><Badge variant="outline">{x.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{x.service} · {x.email}</p><p className="mt-2 line-clamp-2 text-sm">{x.message}</p></button>)}</CardContent></Card>}
   {view==='appointments'&&<Card><CardHeader><CardTitle>Appointments</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex flex-wrap gap-2"><Select value={service} onValueChange={setService}><SelectTrigger className="w-52"><SelectValue placeholder="Service"/></SelectTrigger><SelectContent><SelectItem value="all">All services</SelectItem>{[['video-photo','Video & Photo'],['3d-graphics','3D Graphics'],['motion-graphics','Motion Graphics'],['video-editing','Video Editing']].map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue placeholder="Status"/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{['pending','confirmed','completed','cancelled'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>{bookings.map(x=>{const title=Array.isArray(x.services)?x.services[0]?.title:x.services?.title;return <div key={x.id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{title||x.service_id}</p><p className="text-sm text-muted-foreground">{new Date(x.scheduled_start).toLocaleString()} · Customer {x.user_id}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{x.status}</Badge>{x.status==='pending'&&<Button size="sm" onClick={()=>void updateBooking(x.id,'confirmed')}><CheckCircle2 data-icon="inline-start"/>Confirm</Button>}{x.status==='confirmed'&&<Button size="sm" variant="outline" onClick={()=>void updateBooking(x.id,'completed')}>Complete</Button>}</div></div>})}</CardContent></Card>}
   {view==='customers'&&<Card><CardHeader><CardTitle>Customers</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex gap-2"><Input placeholder="Search name, email, phone" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/><Button variant="outline" onClick={()=>void load()}><Search data-icon="inline-start"/>Search</Button></div>{customers.map(c=><div key={c.email} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-medium">{c.name}</p><p className="text-sm text-muted-foreground">{c.email}{c.phone?` · ${c.phone}`:''}</p></div><div className="flex gap-2"><Badge variant="secondary">{c.bookings} bookings</Badge><Badge variant="outline">{c.inquiries} inquiries</Badge></div></div><p className="mt-2 text-xs text-muted-foreground">Last activity {new Date(c.lastActivity).toLocaleString()}</p></div>)}</CardContent></Card>}
   {view==='services'&&<ServiceManager/>}{view==='settings'&&<Card><CardHeader><CardTitle>Settings</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Admin access and Supabase configuration are managed server-side. No private credentials are exposed in this dashboard.</CardContent></Card>}
   {selected&&<Card className="mt-6"><CardHeader><CardTitle>Request from {selected.name}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><p className="text-sm"><strong>Email:</strong> {selected.email} · <strong>Phone:</strong> {selected.phone||'Not provided'}</p><div className="rounded-lg border p-4 whitespace-pre-wrap text-sm">{selected.message}</div><div className="flex flex-wrap gap-2">{['read','replied','closed'].map(next=><Button key={next} variant="outline" onClick={()=>next==='replied'?updateInquiry(selected.id,{reply}):updateInquiry(selected.id,{status:next})}>{next}</Button>)}</div><Textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Reply to customer" rows={5}/><Button onClick={()=>updateInquiry(selected.id,{reply})} disabled={!reply.trim()}>Send reply</Button></CardContent></Card>}
  </div></div></main><Footer/></>
}
